spring:
  application:
    name: tarkov-service
  management:
    endpoints:
      web:
        exposure:
          include:
            - '*'
tarkov-service:
  tarkov: "production"
  default-value: "Dota 2"